PKGDEST="/var/cache/makepkg/pkg"

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)

CFLAGS="-march=x86-64-v3 -mtune=generic -O3 -fopenmp -ffunction-sections -fdata-sections -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fomit-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -Wl,--gc-sections"
MAKEFLAGS="-j$(nproc)"
RUSTFLAGS="-C opt-level=3 -C codegen-units=1 -C debuginfo=0"
PACKAGER="Orion zhen <https://github.com/Orion-zhen>"
