# .github/workflows/build-stage-2.yml
name: Build Stage 2

on:
  workflow_call:
    secrets: # Define all secrets it needs
      GPG_SEC_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_SIG_KEY:
        required: true

jobs:
  build:
    strategy:
      matrix:
        repos:
          # List from original build-stage-2
          - mihomo
          - wemeet-wayland-screenshare-git
          - calamares-git
          - libastal-git
          - libastal-4-git
          - libastal-cava-git
          - libastal-tray-git
      fail-fast: false
    runs-on: ubuntu-latest
    container: "archlinux:latest"
    permissions:
      contents: write # if checkout is needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SEC_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare environment and Install Dependencies
        run: |
          sed -i '/VerbosePkgLists/d' /etc/pacman.conf
          cat ./configs/makepkg.conf >> /etc/makepkg.conf # Assuming default conf here
          pacman -Syu base-devel git pacman-contrib mold openmp openmpi tree --noconfirm --overwrite '*'
          sed -i '/E_ROOT/d' /usr/bin/makepkg

      - name: Download built packages
        uses: actions/download-artifact@v4.1.8
        with:
          path: x86_64
          merge-multiple: true

      - name: Add tmp repo db
        env:
          GPG_SIG_KEY: ${{ secrets.GPG_SIG_KEY }}
        run: |
          bash scripts/repo-add.sh our-tmp
          echo "[our-tmp]" >> /etc/pacman.conf
          echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
          echo "Server = file://$(pwd)/x86_64" >> /etc/pacman.conf
          pacman -Syu --noconfirm --overwrite '*'

      - name: Build AUR packages
        env:
          GPG_SIG_KEY: ${{ secrets.GPG_SIG_KEY }}
        run: |
          bash scripts/build-one.sh ${{ matrix.repos }}

      - name: Rename illigal characters
        run: |
          find . -maxdepth 1 -type f -name '*:*' | while IFS= read -r file; do mv "$file" "${file//:/_}"; done

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repos }} # Artifact name is the repo name
          path: |
            *.pkg.tar.zst
            *.pkg.tar.zst.sig
          retention-days: 7