name: Clean Workflow Logs

on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean workflow logs
        uses: igorjs/gh-actions-clean-workflow@v7
